#SPDX-License-Identifier: ISC

#ccflags-y += -DDEBUG -Werror -Wall

obj-$(CONFIG_MT7663E) += mt7663e.o
mt7663e-y := pci.o soc.o mmio.o pci_init.o pci_mcu.o pci_mac.o \
	     init.o dma.o eeprom.o main.o mcu.o mac.o debugfs.o
